# .github/workflows/deploy-to-synology.yml
name: CI/CD → Synology
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Build JAR with Maven
        run: mvn -B clean package -DskipTests

      - name: Read version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Update Dockerfile ARG
        run: |
          sed -i "s|ARG APP_VERSION=.*|ARG APP_VERSION=${{ steps.get_version.outputs.version }}|" Dockerfile

      - name: Build Docker image
        run: |
          IMAGE=homeoffice:${{ steps.get_version.outputs.version }}
          docker build --build-arg APP_VERSION=${{ steps.get_version.outputs.version }} -t $IMAGE .

      - name: Save image to TAR
        run: |
          IMAGE=homeoffice:${{ steps.get_version.outputs.version }}
          docker save -o homeoffice-${{ steps.get_version.outputs.version }}.tar $IMAGE
          chmod 644 homeoffice-${{ steps.get_version.outputs.version }}.tar

      - name: Load SSH key into ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Debug SSH from runner
        run: |
          ssh -i id_rsa_deploy -v -o StrictHostKeyChecking=no \
          ${{ secrets.SYNOLOGY_USER }}@${{ secrets.SYNOLOGY_HOST }} \
          'echo SSH OK'

      - name: Save SSH key to file
        run: |
          echo "${{ secrets.SYNOLOGY_SSH_KEY }}" > id_rsa_deploy
          chmod 600 id_rsa_deploy

      - name: Copy TAR into home
        run: |
         scp -o StrictHostKeyChecking=no \
          -i id_rsa_deploy \
         homeoffice-${{ steps.get_version.outputs.version }}.tar \
         ${{ secrets.SYNOLOGY_USER }}@${{ secrets.SYNOLOGY_HOST }}:docker/images/

      - name: Deploy on Synology via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USER }}
          key: ${{ secrets.SYNOLOGY_SSH_KEY }}
          port: ${{ secrets.SYNOLOGY_PORT }}
          script: |
            set -e
            /usr/local/bin/docker load -i /volume1/docker/images/homeoffice-${{ steps.get_version.outputs.version }}.tar
            /usr/local/bin/docker rm -f homeoffice || true
            /usr/local/bin/docker run -d \
              --name homeoffice \
              --restart unless-stopped \
              -p 8077:8077 \
              -v /volume1/web/homeoffice:/app/homeoffice \
              -v /volume1/dysk_docker/homeoffice:/app/homeoffice/disk \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e OPENIA_API_KEY="${{ secrets.OPENIA_API_KEY }}" \
              -e HOME_URL="${{ secrets.HOME_URL }}" \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              homeoffice:${{ steps.get_version.outputs.version }}
     


